### ISSUE TITLE
Using icinga2 demo in Proxied Environment

### ISSUE THREAD

**Issue by jmr567** [Icinga/docker-icinga2-demo#12]
Might be worth adding some notes to the README .md for using this setup in a proxied environment. Most corporate environments have a proxy and this would prevent many users spinning up this demo. 

If external internet access is not available the container will print

`2017/03/02:04:40:42 Fetching latest icinga* snapshot packages.`

then exit. 

By passing the proxy environment variables you can get things working

Example:
`docker run -ti --name icinga2 -e "http_proxy=http://proxy.example.com:8080" -e "https_proxy=https://proxy.example.com:8080" -p 3080:80 icinga/icinga2`

Happy to also accept people should understand how to run docker in a proxied environment and leave things as they are, however I think it may be helpful for others.

**Comment by Hipska** [comment]
In my opinion, the container should not do that. Let Docker handle that by itself.
