### ISSUE TITLE
problem restarting container (mysql database errors)

### ISSUE THREAD

**Issue by mvillarejo** [Icinga/docker-icinga2-demo#13]
Hello, it seems that the init.done flag is not really working and the containter tries to apply the schema on every start throwing duplicate column name errors:

icinga2.docker.local_1   | 170310 11:19:48 [Note] /usr/libexec/mysqld (mysqld 5.5.50-MariaDB) starting as process 215 ...
icinga2.docker.local_1   | ERROR 1060 (42S21) at line 1436: Duplicate column name 'endpoint_object_id'

regards

**Comment by afend69** [comment]
Hi, I have also the same problem. I'm using Docker data volume for /var/lib/mysql with -v option. When I stop container, remove it and re-create on start I get in log:

170323 15:08:36 [Note] /usr/libexec/mysqld (mysqld 5.5.52-MariaDB) starting as process 190 ...
170323 15:08:36 [ERROR] mysqld: Table './mysql/db' is marked as crashed and should be repaired
170323 15:08:36 [Warning] Checking table:   './mysql/db'
170323 15:08:36 [ERROR] mysql.db: 1 client is using or hasn't closed the table properly
170323 15:08:36 [Note] /usr/libexec/mysqld (mysqld 5.5.52-MariaDB) starting as process 197 ...
ERROR 1060 (42S21) at line 1436: Duplicate column name 'endpoint_object_id'

Regards
