### ISSUE TITLE
Use docker compose and multiple containers

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/docker-icinga2-demo#7]
This should the following containers

- icinga2
- icingaweb2 (apache)
- mysql

Once icinga2/icingaweb2 are started they should check for the MySQL database and schema and optionally provision it automatically.

Discuss.

**Comment by lazyfrosch** [comment]
Yes, absolutely makes sense.

I would op for having icinga2 + icingaweb2 in separate GIT repositories.

MySQL can be served from official MariaDB or MySQL container, with a proper compose file / docs

**Comment by dnsmichi** [comment]
I had a chat with Christoph (https://github.com/psi-4ward) during the birthday party on the weekend, and he's willing to contribute here.

**Comment by lazyfrosch** [comment]
You meant @psi-4ward ?

**Comment by psi-4ward** [comment]
Hey yeah, good to mention me so I got a mail.
I've a Icinga2 and Icingaweb2 Container with DB-Init/Update and kickstart scripts but I think its better to get rid of the director-kickstart and pull in some sane defaults (I need your help here).

Where should I publish the stuff? On my Github account an we'll discuss it there and probably merge it to any official icinga repo??

**Comment by dnsmichi** [comment]
Hi, thanks for the feedback :)

Director is probably a second step, I would focus on the initial thingy first. Would you go for separate repos, or put everything into one (with sub dirs)?

**Comment by psi-4ward** [comment]
I tend to separate Repos. The tags should follow the versioing and it makes the automated docker builds more easy.

**Comment by dnsmichi** [comment]
Ok then, could you go for your own repos and we keep the discussion going :)

**Comment by lazyfrosch** [comment]
I would love to see some simple images to start with, if you want to maintain them we can move them to Icinga's namespace and give you all the access you need.

**Comment by psi-4ward** [comment]
First one: https://github.com/psi-4ward/docker-icinga2

**Comment by psi-4ward** [comment]
Icingaweb2: https://github.com/psi-4ward/docker-icingaweb2

Draft of the compose file: https://gist.github.com/psi-4ward/c247863b52104a8c993649896065bd49

**Comment by bodsch** [comment]
i use this for a long time.
3 containers for this environment. ;)
take a look at bodsch/docker-icinga2 bodsch/docker-icingaweb2 and bodsch/docker-mysql
