### ISSUE TITLE
Delete httpd.pid in start process

### ISSUE THREAD

**Issue by monotek** [Icinga/docker-icinga2-demo#8]
While testing some stuff in the container i restarted it several times. Unfortunately at some point the httpd daemon did not start anymore because the old pidfile was still there and it claimed "already running".

Deleting the pidfile solved the problem.

So maybe its a good idea to delete old pidfiles in the start process of the container.

**Comment by rprihoda** [comment]
I ran into this bug today as well.

**Comment by rprihoda** [comment]
For the record I added an if statement right before you call supervisord in the dockerfile. it seems to be working fine. 
```
if [ -f /run/httpd/httpd.pid ]; then
        rm /run/httpd/httpd.pid
fi
```

**Comment by monotek** [comment]
Why "wontfix"?

**Comment by dnsmichi** [comment]
See #16.
